
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sciftjvjlpemhkvtokhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjaWZ0anZqbHBlbWhrdnRva2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjM2NTAsImV4cCI6MjA2NDYzOTY1MH0.ZgUBFxEKroZg3tkVbrON0-D3heyydoIg_Uvjs3l2YCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
